[tokens]
    [tokens.user1]
        user = "user1"
        token = "token1"
        comment = "user1 with token1"
        ports = [8080, "10000-10200"]
        domains = ["web01.domain.com", "web02.domain.com"]
        subdomains = ["web01", "web02"]
        enable = false
        server = ""
        create_date = ""
        expire_date = ""
    [tokens.user2]
        user = "user2"
        token = "token2"
        comment = "user2 with token2"
        ports = [9080]
        domains = ["web11.domain.com", "web12.domain.com"]
        subdomains = ["web11", "web12"]
        enable = false
        server = ""
        create_date = ""
        expire_date = ""
    [tokens.xx1]
        user = "xx1"
        token = "ssxxx"
        comment = ""
        ports = [""]
        domains = [""]
        subdomains = [""]
        enable = true
        server = "Default FRP Server"
        create_date = "2025-09-01 18:25:11"
        expire_date = "2025-09-30 00:00:00"
