[tokens]
  [tokens.user1]
    user = "user1"
    token = "token1"
    comment = "张三"
    ports = [""]
    domains = [""]
    subdomains = [""]
    status = true
  [tokens.user2]
    user = "user2"
    token = "token2"
    comment = "李四"
    ports = [""]
    domains = [""]
    subdomains = [""]
    status = true
