[tokens]
    [tokens.AhmayF]
        user = "AhmayF"
        token = "ahCf7bEn7v4N8sIhAKkKkGvUofaQvi2B"
        comment = ""
        ports = ["10216-10219"]
        domains = [""]
        subdomains = [""]
        enable = true
        server = "Default FRP Server"
        create_date = "2025-09-02 11:07:57"
        expire_date = "2025-09-30 00:00:00"
    [tokens.LPuZOC]
        user = "LPuZOC"
        token = "tgBS1gH15lmy48SSFqQ2jf00AvWwqKTF"
        comment = ""
        ports = ["10223-10253"]
        domains = [""]
        subdomains = [""]
        enable = true
        server = "Default FRP Server"
        create_date = "2025-09-02 16:09:42"
        expire_date = "2025-09-30 00:00:00"
    [tokens.Rdrake]
        user = "Rdrake"
        token = "xndkTR0b9sLXh6hEdaTD7Tbf8rGlAvi8"
        comment = ""
        ports = [10201, 10202, 10203, 10204]
        domains = [""]
        subdomains = [""]
        enable = true
        server = "Default FRP Server"
        create_date = "2025-09-02 11:05:31"
        expire_date = "2025-09-30 00:00:00"
    [tokens.cRMlCP]
        user = "cRMlCP"
        token = "rhJDw5HAAafJMlHnNxODWQFJIfJAFgzI"
        comment = ""
        ports = ["10000-10020"]
        domains = [""]
        subdomains = [""]
        enable = true
        server = "Another FRP Server"
        create_date = "2025-09-02 16:15:24"
        expire_date = "2025-09-30 00:00:00"
    [tokens.klQpfU]
        user = "klQpfU"
        token = "W2yHnjAaY339USJDtefxei1plJprJQ6e"
        comment = ""
        ports = ["10254-10264"]
        domains = [""]
        subdomains = [""]
        enable = true
        server = "Default FRP Server"
        create_date = "2025-09-02 16:13:21"
        expire_date = "2025-09-30 00:00:00"
    [tokens.user1]
        user = "user1"
        token = "token1"
        comment = "user1 with token1"
        ports = [8080, "10000-10200"]
        domains = ["web01.domain.com", "web02.domain.com"]
        subdomains = ["web01", "web02"]
        enable = false
        server = "未配置"
        create_date = "未配置"
        expire_date = "2025-09-30 00:00:00"
    [tokens.user2]
        user = "user2"
        token = "token2"
        comment = "user2 with token2"
        ports = [9080]
        domains = ["web11.domain.com", "web12.domain.com"]
        subdomains = ["web11", "web12"]
        enable = false
        server = ""
        create_date = ""
        expire_date = ""
