[tokens]
    [tokens.AhmayF]
        user = "AhmayF"
        token = "ahCf7bEn7v4N8sIhAKkKkGvUofaQvi2B"
        comment = ""
        ports = ["10216-10219"]
        domains = [""]
        subdomains = [""]
        enable = true
        server = "Default FRP Server"
        create_date = "2025-09-02 11:07:57"
        expire_date = "2025-09-30 00:00:00"
    [tokens.qKOatV]
        user = "qKOatV"
        token = "xndkTR0b9sLXh6hEdaTD7Tbf8rGlAvi8"
        comment = ""
        ports = [10201, 10202, 10203, 10204]
        domains = [""]
        subdomains = [""]
        enable = true
        server = "Default FRP Server"
        create_date = "2025-09-02 11:05:31"
        expire_date = "2025-09-30 00:00:00"
    [tokens.tZfaDA]
        user = "tZfaDA"
        token = "gJQ3YcgfHNziRZh61UIH22Lpjbr8BgwJ"
        comment = ""
        ports = [10205, 10206, 10207, 10208, 10209, 10210, 10211, 10212, 10213, 10214, 10215]
        domains = [""]
        subdomains = [""]
        enable = true
        server = "Default FRP Server"
        create_date = "2025-09-02 11:06:23"
        expire_date = "2025-09-02 00:00:00"
    [tokens.user1]
        user = "user1"
        token = "token1"
        comment = "user1 with token1"
        ports = [8080, "10000-10200"]
        domains = ["web01.domain.com", "web02.domain.com"]
        subdomains = ["web01", "web02"]
        enable = false
        server = ""
        create_date = ""
        expire_date = ""
    [tokens.user2]
        user = "user2"
        token = "token2"
        comment = "user2 with token2"
        ports = [9080]
        domains = ["web11.domain.com", "web12.domain.com"]
        subdomains = ["web11", "web12"]
        enable = false
        server = ""
        create_date = ""
        expire_date = ""
    [tokens.xx1]
        user = "xx1"
        token = "ssxxx"
        comment = ""
        ports = [""]
        domains = [""]
        subdomains = [""]
        enable = true
        server = "Default FRP Server"
        create_date = "2025-09-01 18:25:11"
        expire_date = "2025-09-31 00:00:00"
    [tokens.xxx2]
        user = "xxx2"
        token = "xxxxxx"
        comment = ""
        ports = [""]
        domains = [""]
        subdomains = [""]
        enable = true
        server = "Another FRP Server"
        create_date = "2025-09-02 09:23:40"
        expire_date = "2025-09-30 00:00:00"
